### ISSUE TITLE
Analytics/Event and status of ZPM-Registry

### ISSUE THREAD

**Issue by CraigRegester** [intersystems-community/zpm-registry#99]
Good afternoon!

I'm working with a team exploring the use of the ZPM Registry to better support our downstream clients. In the interest of capturing usage of tools, solutions, and modules it makes logical sense to capture some basic analytics.

I noted in the GetArchive method of Registry.cls captures some data using the Analytics/Event.cls class but there is also a class referenced in that method that doesn't exist in the master branch - ZPM.Analytics.IP - unclear what the intent is there or maybe a scrapped feature.

https://github.com/intersystems-community/zpm-registry/blob/6831c2501f29deb1a381138d21c4b8482d396d62/src/cls/ZPM/Analytics/Event.cls#L52C13-L52C59

Ideally, it would be possible to augment the registration process to a new private registry such that some details about the client connecting are captured at registration by the ZPM-Registry entrance (e.g., customer name, etc).

The zpm-registry repo has been a bit stale recently - are there plans to make any further enhancements and/or brand ipm-registry similar to what was done with ZPM->IPM prior to including other changes/features? Or if some fixes are submitted via pull request, will they still be considered at this time?

Thanks!

**Comment by nsolov** [comment]
Since version 1.2.7 the new approach for post-processing events implemented.

To execute your code after the analytics event occurs, you should implement a subclass of the ZPM.Analytics.AbstractEventProcessor class
and override the method: ClassMethod Process(event as ZPM.Analytics.Event) As %Status.

The best way to identify users is to use tokens.
In IPM the user can specify personal token in `repo` command:
`zpm:USER>repo -r -n registry -url https://your-domain.com/registry/ -token <personalToken>`

In Registry code (in the `Process` method) you can get token value with 
`Set token = %request.GetCgiEnv("HTTP_APIKEY","")`

You can configure IAM to work with tokens, and specify in IAM which registry endpoints will be available for users with no token, and with specific tokens.

**Comment by evshvarov** [comment]
@CraigRegester , please close the ticket if you think it is solved! Thank you!

**Comment by CraigRegester** [comment]
@evshvarov Apologies, didn't mean to leave this hanging. While it might not presently be ideal how it is handled, we have been able to make do so I will close the ticket for now. I know there is some efforts at ISC underway to work on the IPM infrastructure as a whole so likely will see some improvements over time there.

Happy New Year!
